apiVersion: v1
kind: Namespace
metadata:
  name: kubuk-testr

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: kubuk-testr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: roman2447/roman_db:latest
          ports:
            - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: kubuk-testr
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: kubuk-testr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: roman2447/facebook-client:tagname
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: kubuk-testr
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: kubuk-testr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: roman2447/facebook-server:tagname
          ports:
            - containerPort: 5181

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: kubuk-testr
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5174
      targetPort: 5174
  type: LoadBalancer
